// 한국 재활/치료실 흔한 도구 사전 정의 30개.
// 게임 mdx의 materials 자유 텍스트와 aliases로 자동 매칭.
// 가격은 다이소/네이버 기준 일반 시세 (2026년 추정).

export type ToolCategory =
  | "ball"
  | "rod"
  | "card"
  | "sport"
  | "kitchen"
  | "craft"
  | "furniture"
  | "misc";

export type ToolType = "consumable" | "durable";

export interface ToolDef {
  id: string;
  name: string; // 한국어
  nameEn?: string;
  category: ToolCategory;
  type: ToolType;
  priceMin: number; // 원, 0이면 "치료실 기본 구비"
  priceMax: number;
  priceNote?: string;
  aliases: string[]; // materials 텍스트 매칭용 (소문자 비교)
  description?: string;
}

export const CATEGORY_LABELS: Record<ToolCategory, string> = {
  ball: "공",
  rod: "막대",
  card: "카드",
  sport: "운동기구",
  kitchen: "주방",
  craft: "공예",
  furniture: "가구",
  misc: "잡화",
};

export const TYPE_LABELS: Record<ToolType, string> = {
  consumable: "소비재",
  durable: "영구재",
};

export const TOOLS_MASTER: ToolDef[] = [
  {
    id: "balloon",
    name: "풍선",
    category: "misc",
    type: "consumable",
    priceMin: 1000,
    priceMax: 5000,
    priceNote: "30개 묶음 기준",
    aliases: ["풍선", "큰 풍선", "balloon"],
    description: "가벼움·안전·노인 그룹 게임 단골. 펌프 함께 권장.",
  },
  {
    id: "pingpong-ball",
    name: "탁구공",
    category: "ball",
    type: "durable",
    priceMin: 3000,
    priceMax: 10000,
    priceNote: "10-20개 묶음",
    aliases: ["탁구공"],
    description: "정밀 던지기·잡기에 표준. 색깔별 묶음 권장.",
  },
  {
    id: "paper-cone",
    name: "접시콘",
    category: "sport",
    type: "durable",
    priceMin: 5000,
    priceMax: 20000,
    priceNote: "6-12개 세트",
    aliases: ["접시콘", "콘"],
    description: "거리·표적 표시·골 영역에 다용도.",
  },
  {
    id: "paper-cup",
    name: "종이컵",
    category: "misc",
    type: "consumable",
    priceMin: 2000,
    priceMax: 5000,
    priceNote: "50-100개 묶음",
    aliases: ["종이컵", "컵"],
    description: "당구·골프·스태킹·점수통 모두 가능한 만능 도구.",
  },
  {
    id: "plastic-cup",
    name: "플라스틱 컵 (스태킹)",
    category: "craft",
    type: "durable",
    priceMin: 10000,
    priceMax: 25000,
    priceNote: "12-21개 세트",
    aliases: ["스태킹", "스태킹 컵", "컵 쌓기"],
    description: "컵 쌓기·날리기 전용. 종이컵보다 안정적.",
  },
  {
    id: "clothespin",
    name: "빨래집게",
    category: "craft",
    type: "durable",
    priceMin: 2000,
    priceMax: 5000,
    priceNote: "30-50개 묶음, 강도별 권장",
    aliases: ["빨래집게"],
    description: "핀치력 단계화에 필수. 약·중·강 강도별로 갖추면 이상적.",
  },
  {
    id: "kitchen-tongs",
    name: "요리 집게",
    category: "kitchen",
    type: "durable",
    priceMin: 3000,
    priceMax: 10000,
    aliases: ["요리 집게", "집게", "핀셋"],
    description: "콩·솜공 옮기기 등 정밀 도구 사용 task에 적합.",
  },
  {
    id: "scarf",
    name: "시폰 스카프",
    category: "craft",
    type: "durable",
    priceMin: 5000,
    priceMax: 15000,
    priceNote: "6-12장 색깔별",
    aliases: ["스카프", "시폰", "천"],
    description: "가볍고 부드러워 던지기·휘두르기 모두 안전.",
  },
  {
    id: "frying-pan-toy",
    name: "장난감 프라이팬",
    category: "kitchen",
    type: "durable",
    priceMin: 5000,
    priceMax: 15000,
    aliases: ["프라이팬", "팬"],
    description: "부침개 뒤집기 등 ADL 시뮬레이션에 필수. 가벼운 것만.",
  },
  {
    id: "spatula-toy",
    name: "뒤집개",
    category: "kitchen",
    type: "durable",
    priceMin: 2000,
    priceMax: 5000,
    aliases: ["뒤집개"],
    description: "실리콘 권장. 손목 회내·외 운동 task의 핵심.",
  },
  {
    id: "jenga",
    name: "젠가",
    category: "craft",
    type: "durable",
    priceMin: 10000,
    priceMax: 30000,
    aliases: ["젠가"],
    description: "양손 협응·집중력. 어르신 인기.",
  },
  {
    id: "yutnori",
    name: "윷놀이",
    category: "craft",
    type: "durable",
    priceMin: 5000,
    priceMax: 20000,
    aliases: ["윷", "윷놀이"],
    description: "전통 게임. 던지기 + 사회적 참여 + 회상 자극.",
  },
  {
    id: "mini-curling",
    name: "미니 컬링",
    category: "sport",
    type: "durable",
    priceMin: 20000,
    priceMax: 50000,
    aliases: ["미니컬링", "컬링"],
    description: "거리 조절·전략. 좌석에서도 가능.",
  },
  {
    id: "toy-gun",
    name: "장난감 총",
    category: "sport",
    type: "durable",
    priceMin: 5000,
    priceMax: 30000,
    aliases: ["장난감 총", "총"],
    description: "조준·인지·재미. 안전한 폼탄/물총 권장.",
  },
  {
    id: "gym-ball",
    name: "짐볼",
    category: "ball",
    type: "durable",
    priceMin: 15000,
    priceMax: 40000,
    priceNote: "직경 45-65cm",
    aliases: ["짐볼", "큰 공", "큰 부드러운 공"],
    description: "체간 안정·그룹 패스 게임. 가벼울수록 좋음.",
  },
  {
    id: "soft-ball",
    name: "소프트 볼",
    category: "ball",
    type: "durable",
    priceMin: 3000,
    priceMax: 10000,
    aliases: ["소프트볼", "부드러운 공", "축구공", "농구공", "볼풀공"],
    description: "안전한 던지기·차기. 어르신·아동 모두.",
  },
  {
    id: "bowling-pin",
    name: "볼링핀",
    category: "sport",
    type: "durable",
    priceMin: 10000,
    priceMax: 25000,
    priceNote: "5-10개 세트 (페트병으로 대체 가능)",
    aliases: ["볼링핀", "볼링", "페트병"],
    description: "쓰러뜨리기 표적. 페트병에 물 조금 넣으면 대체 가능.",
  },
  {
    id: "pvc-pole",
    name: "PVC 봉·수영 누들",
    category: "rod",
    type: "durable",
    priceMin: 3000,
    priceMax: 15000,
    priceNote: "수영 누들 1개 3-5천원",
    aliases: ["pvc", "수영 누들", "누들", "봉", "큐", "막대"],
    description: "가볍고 안전한 막대·봉. 당구 큐·하키 채·치기 도구로 다용도.",
  },
  {
    id: "picture-cards",
    name: "그림 카드",
    category: "card",
    type: "durable",
    priceMin: 3000,
    priceMax: 15000,
    priceNote: "16-30장 세트",
    aliases: ["그림 카드", "카드"],
    description: "기억력 짝짓기·인지 분류. 대비 강한 이미지 권장.",
  },
  {
    id: "golf-ball",
    name: "골프공·작은 공",
    category: "ball",
    type: "durable",
    priceMin: 5000,
    priceMax: 15000,
    aliases: ["골프공", "작은 공"],
    description: "손골프·정밀 굴리기. 부드러운 폼볼이 안전.",
  },
  {
    id: "color-chips",
    name: "색·숫자 칩",
    category: "craft",
    type: "consumable",
    priceMin: 5000,
    priceMax: 10000,
    priceNote: "30-50개 묶음",
    aliases: ["색깔 칩", "칩", "색·숫자", "색깔 스티커", "스티커", "색깔 압정"],
    description: "색 변별·인지 분류 task. 3cm 이상 크기 권장.",
  },
  {
    id: "beans-mixed",
    name: "잡곡·콩",
    category: "misc",
    type: "consumable",
    priceMin: 3000,
    priceMax: 8000,
    priceNote: "각 종류 200-300g",
    aliases: ["콩", "강낭콩", "검정콩", "렌즈콩", "완두콩"],
    description: "분류 task용. 알레르기·삼킴 주의.",
  },
  {
    id: "griptok",
    name: "그립톡·캐릭터 인형",
    category: "misc",
    type: "durable",
    priceMin: 5000,
    priceMax: 15000,
    aliases: ["그립톡", "캐릭터 인형", "인형"],
    description: "안구 추적 시각 자극용 손에 들기 좋은 작은 물체.",
  },
  {
    id: "mat",
    name: "안전 매트",
    category: "furniture",
    type: "durable",
    priceMin: 20000,
    priceMax: 100000,
    aliases: ["매트", "안전 매트"],
    description: "선 자세 게임 시 낙상 완충.",
  },
  {
    id: "table",
    name: "테이블",
    category: "furniture",
    type: "durable",
    priceMin: 0,
    priceMax: 0,
    priceNote: "치료실 기본 구비",
    aliases: ["테이블"],
    description: "팔꿈치 90°가 되는 높이가 이상적.",
  },
  {
    id: "chair",
    name: "의자·휠체어",
    category: "furniture",
    type: "durable",
    priceMin: 0,
    priceMax: 0,
    priceNote: "치료실 기본 구비",
    aliases: ["의자", "휠체어"],
    description: "좌석 안정성·브레이크 잠금 점검 필수.",
  },
  {
    id: "timer",
    name: "초시계·타이머",
    category: "misc",
    type: "durable",
    priceMin: 3000,
    priceMax: 15000,
    aliases: ["초시계", "타이머"],
    description: "스마트폰 타이머로 대체 가능.",
  },
  {
    id: "music-player",
    name: "음악 재생기",
    category: "misc",
    type: "durable",
    priceMin: 0,
    priceMax: 0,
    priceNote: "스마트폰 + 스피커로 충분",
    aliases: ["음악", "재생기", "배경 음악", "탬버린", "응원 도구"],
    description: "리듬 게임·박자 동기화에 필요. 60-90 BPM 권장. 탬버린 등 응원 도구 포함.",
  },
  {
    id: "tape-marker",
    name: "마스킹 테이프",
    category: "craft",
    type: "consumable",
    priceMin: 2000,
    priceMax: 5000,
    aliases: ["테이프", "출발선", "측정선", "마스킹", "표시선", "거리 표시", "리본", "페그"],
    description: "거리 표시·출발선 등에 다용도.",
  },
  {
    id: "vinyl-tunnel",
    name: "비닐 터널",
    category: "sport",
    type: "consumable",
    priceMin: 10000,
    priceMax: 30000,
    aliases: ["비닐터널", "터널"],
    description: "유아·소집단 운동에 인기. 사용 빈도에 따라 1-2년 교체.",
  },
  {
    id: "cotton-ball",
    name: "솜공·작은 물건",
    category: "misc",
    type: "consumable",
    priceMin: 3000,
    priceMax: 8000,
    aliases: ["솜공", "구슬", "작은 물건"],
    description: "집게·핀셋 task에 옮길 대상. 색깔별 묶음.",
  },
  {
    id: "whiteboard",
    name: "점수판·화이트보드",
    category: "furniture",
    type: "durable",
    priceMin: 10000,
    priceMax: 50000,
    aliases: ["점수판", "화이트보드"],
    description: "팀 점수·라운드 기록. 종이로 대체 가능.",
  },
  {
    id: "sorting-bowl",
    name: "분류 그릇·바구니",
    category: "misc",
    type: "durable",
    priceMin: 2000,
    priceMax: 10000,
    priceNote: "3-6개 세트",
    aliases: [
      "분류 그릇",
      "분류용",
      "분류판",
      "색별 그릇",
      "그릇",
      "바구니",
      "트레이",
      "아이스박스",
      "쿨러",
    ],
    description: "색·크기별 분류 task의 목표 용기. 던지기 표적으로도 활용.",
  },
  {
    id: "beach-ball",
    name: "비치볼",
    category: "ball",
    type: "durable",
    priceMin: 2000,
    priceMax: 8000,
    aliases: ["비치볼"],
    description: "크고 가벼워 느린 궤적. 좌석 패스·치기에 안전.",
  },
  {
    id: "origami-paper",
    name: "색종이·종이접기",
    category: "craft",
    type: "consumable",
    priceMin: 1000,
    priceMax: 5000,
    priceNote: "100매 묶음",
    aliases: ["색종이", "종이접기", "종이 접기", "색지", "종이 개구리", "개구리"],
    description: "접기·꾸미기 소근육 task. 산타·개구리·박 속 채우기 등.",
  },
  {
    id: "mirror",
    name: "거울",
    category: "misc",
    type: "durable",
    priceMin: 3000,
    priceMax: 15000,
    aliases: ["거울"],
    description: "표정·자세 셀프 피드백. 미용·웃음·동작 모방에 활용.",
  },
  {
    id: "refreshments",
    name: "다과·차·간식",
    category: "misc",
    type: "consumable",
    priceMin: 5000,
    priceMax: 20000,
    aliases: ["다과", "간식", "떡국", "명절 음식", "차·", "선물"],
    description: "회상·명절·마무리 활동의 사회적 윤활유. 알레르기·당뇨 점검 필수.",
  },
  {
    id: "comb-brush",
    name: "빗·브러시·미용 도구",
    category: "craft",
    type: "durable",
    priceMin: 2000,
    priceMax: 10000,
    aliases: ["빗", "브러시", "드라이어", "미용 가운", "가운", "머리핀", "머리띠", "헤어"],
    description: "미용사 역할극용. 안전 소재·장난감 가위만.",
  },
  {
    id: "hook-fishing",
    name: "갈고리·낚시 도구",
    category: "sport",
    type: "durable",
    priceMin: 5000,
    priceMax: 20000,
    aliases: ["갈고리", "후크", "낚싯대", "낚시", "자석 낚시"],
    description: "걸기·낚기 정밀 task. 끝 부분 안전 처리 필수.",
  },
  {
    id: "chopsticks",
    name: "젓가락",
    category: "kitchen",
    type: "durable",
    priceMin: 1000,
    priceMax: 5000,
    aliases: ["젓가락", "나무젓가락"],
    description: "집기 정밀 운동. 긴 나무젓가락이 잡기 쉬움.",
  },
  {
    id: "egg-tray",
    name: "종이 계란판",
    category: "misc",
    type: "consumable",
    priceMin: 0,
    priceMax: 2000,
    priceNote: "재활용 가능",
    aliases: ["계란판"],
    description: "탁구공 넣기·분류 표적. 재활용으로 무료 조달 가능.",
  },
  {
    id: "fan",
    name: "부채",
    category: "craft",
    type: "durable",
    priceMin: 2000,
    priceMax: 10000,
    aliases: ["부채"],
    description: "부치기 동작 = 어깨·손목 ROM + 전통 회상.",
  },
  {
    id: "floorball-set",
    name: "플로어볼 세트",
    category: "sport",
    type: "durable",
    priceMin: 10000,
    priceMax: 30000,
    aliases: ["플로어볼"],
    description: "구멍 뚫린 가벼운 공 + 플라스틱 채. 안전한 하키·골프.",
  },
  {
    id: "gimbap-mat",
    name: "김발 (김말이판)",
    category: "kitchen",
    type: "durable",
    priceMin: 2000,
    priceMax: 8000,
    aliases: ["김발", "김말이", "김밥 재료"],
    description: "말기 동작 = 양손 협응 + 한식 ADL 회상.",
  },
  {
    id: "hula-hoop",
    name: "훌라후프",
    category: "sport",
    type: "durable",
    priceMin: 5000,
    priceMax: 15000,
    aliases: ["훌라후프"],
    description: "굴리기·돌리기·표적. 성인용 50-70cm.",
  },
  {
    id: "mallet",
    name: "뿅망치·방망이",
    category: "sport",
    type: "durable",
    priceMin: 3000,
    priceMax: 10000,
    aliases: ["뿅망치", "방망이"],
    description: "두드리기 동작. 스폰지 재질로 안전.",
  },
  {
    id: "rubber-band",
    name: "고무줄",
    category: "craft",
    type: "consumable",
    priceMin: 1000,
    priceMax: 3000,
    priceNote: "컬러 고무줄 묶음",
    aliases: ["고무줄"],
    description: "걸기·연결 소근육 task. 얇은 컬러 고무줄.",
  },
  {
    id: "s-hook",
    name: "S고리",
    category: "craft",
    type: "durable",
    priceMin: 2000,
    priceMax: 5000,
    priceNote: "다이소 다양한 크기",
    aliases: ["s고리", "에스고리"],
    description: "걸기 정밀 task. 크기별로 난이도 단계화.",
  },
  {
    id: "jegi",
    name: "제기",
    category: "sport",
    type: "durable",
    priceMin: 1000,
    priceMax: 5000,
    aliases: ["제기"],
    description: "차기·토스 전통 놀이. 좌석에서 손 토스도 가능.",
  },
  {
    id: "blindfold",
    name: "안대·눈가리개",
    category: "misc",
    type: "durable",
    priceMin: 2000,
    priceMax: 8000,
    aliases: ["안대", "눈가리개", "가리개"],
    description: "시각 차단으로 촉각·청각 의존 task. 전정·감각 훈련.",
  },
  {
    id: "indoor-shoe",
    name: "실내 신발·슬리퍼",
    category: "misc",
    type: "durable",
    priceMin: 0,
    priceMax: 10000,
    aliases: ["신발", "슬리퍼"],
    description: "던지기 표적·전통 신발 던지기. 실내용 소독 후 사용.",
  },
  {
    id: "racket-set",
    name: "라켓 세트",
    category: "sport",
    type: "durable",
    priceMin: 10000,
    priceMax: 30000,
    aliases: ["라켓", "셔틀콕"],
    description: "탁구·배드민턴 라켓. 어린이용 가벼운 것 권장.",
  },
  {
    id: "paper-pen",
    name: "메모지·필기구",
    category: "misc",
    type: "consumable",
    priceMin: 2000,
    priceMax: 8000,
    aliases: ["메모지", "필기구", "메모", "달력", "포스트잇"],
    description: "회상·목표 작성. 달력은 시각 단서로 활용.",
  },
  {
    id: "toy-tools",
    name: "장난감 공구 세트",
    category: "craft",
    type: "durable",
    priceMin: 10000,
    priceMax: 30000,
    aliases: ["공구", "나사", "볼트", "드라이버", "렌치"],
    description: "조립·돌리기 = 손목 회전 + 정밀 task. 큰 사이즈 권장.",
  },
  {
    id: "soft-block",
    name: "스폰지 블록·벽돌 모형",
    category: "craft",
    type: "durable",
    priceMin: 5000,
    priceMax: 20000,
    aliases: ["블록", "벽돌", "스폰지 블록"],
    description: "쌓기·쓰러뜨리기. 가벼운 스폰지로 안전.",
  },
  {
    id: "novelty-toy",
    name: "깜짝·서프라이즈 도구",
    category: "misc",
    type: "consumable",
    priceMin: 3000,
    priceMax: 15000,
    aliases: ["팝파레", "콘페티", "뱀스프링", "도깨비 상자", "깜짝", "서프라이즈"],
    description: "예측 불가 자극 = 즉각 웃음. 심장·불안 환자 주의.",
  },
  {
    id: "ladderball-set",
    name: "레더볼 세트",
    category: "sport",
    type: "durable",
    priceMin: 30000,
    priceMax: 70000,
    priceNote: "사다리 1쌍 + 공 끈 6쌍",
    aliases: ["레더볼", "사다리"],
    description: "끈 연결 공을 사다리에 걸기. 뉴스포츠·점수 명확.",
  },
  {
    id: "button-board",
    name: "단추·지퍼 보드",
    category: "craft",
    type: "durable",
    priceMin: 3000,
    priceMax: 12000,
    aliases: ["단추", "지퍼", "옷걸이"],
    description: "잠그기·풀기 = 대표적 ADL 소근육 task.",
  },
  {
    id: "decoration",
    name: "장식·트리 소품",
    category: "craft",
    type: "consumable",
    priceMin: 5000,
    priceMax: 20000,
    aliases: ["장식", "트리", "오너먼트", "양말 + 작은 선물"],
    description: "명절·계절 분위기 조성. 크리스마스 트리·오너먼트 등.",
  },
];

export function getToolById(id: string): ToolDef | undefined {
  return TOOLS_MASTER.find((t) => t.id === id);
}
