// 한국 재활/치료실 흔한 도구 사전 정의 30개.
// 게임 mdx의 materials 자유 텍스트와 aliases로 자동 매칭.
// 가격은 다이소/네이버 기준 일반 시세 (2026년 추정).

export type ToolCategory =
  | "ball"
  | "rod"
  | "card"
  | "sport"
  | "kitchen"
  | "craft"
  | "furniture"
  | "misc";

export type ToolType = "consumable" | "durable";

export interface ToolDef {
  id: string;
  name: string; // 한국어
  nameEn?: string;
  category: ToolCategory;
  type: ToolType;
  priceMin: number; // 원, 0이면 "치료실 기본 구비"
  priceMax: number;
  priceNote?: string;
  aliases: string[]; // materials 텍스트 매칭용 (소문자 비교)
  description?: string;
}

export const CATEGORY_LABELS: Record<ToolCategory, string> = {
  ball: "공",
  rod: "막대",
  card: "카드",
  sport: "운동기구",
  kitchen: "주방",
  craft: "공예",
  furniture: "가구",
  misc: "잡화",
};

export const TYPE_LABELS: Record<ToolType, string> = {
  consumable: "소비재",
  durable: "영구재",
};

export const TOOLS_MASTER: ToolDef[] = [
  {
    id: "balloon",
    name: "풍선",
    category: "misc",
    type: "consumable",
    priceMin: 1000,
    priceMax: 5000,
    priceNote: "30개 묶음 기준",
    aliases: ["풍선", "큰 풍선", "balloon"],
    description: "가벼움·안전·노인 그룹 게임 단골. 펌프 함께 권장.",
  },
  {
    id: "pingpong-ball",
    name: "탁구공",
    category: "ball",
    type: "durable",
    priceMin: 3000,
    priceMax: 10000,
    priceNote: "10-20개 묶음",
    aliases: ["탁구공"],
    description: "정밀 던지기·잡기에 표준. 색깔별 묶음 권장.",
  },
  {
    id: "paper-cone",
    name: "접시콘",
    category: "sport",
    type: "durable",
    priceMin: 5000,
    priceMax: 20000,
    priceNote: "6-12개 세트",
    aliases: ["접시콘", "콘"],
    description: "거리·표적 표시·골 영역에 다용도.",
  },
  {
    id: "paper-cup",
    name: "종이컵",
    category: "misc",
    type: "consumable",
    priceMin: 2000,
    priceMax: 5000,
    priceNote: "50-100개 묶음",
    aliases: ["종이컵", "컵"],
    description: "당구·골프·스태킹·점수통 모두 가능한 만능 도구.",
  },
  {
    id: "plastic-cup",
    name: "플라스틱 컵 (스태킹)",
    category: "craft",
    type: "durable",
    priceMin: 10000,
    priceMax: 25000,
    priceNote: "12-21개 세트",
    aliases: ["스태킹", "스태킹 컵", "컵 쌓기"],
    description: "컵 쌓기·날리기 전용. 종이컵보다 안정적.",
  },
  {
    id: "clothespin",
    name: "빨래집게",
    category: "craft",
    type: "durable",
    priceMin: 2000,
    priceMax: 5000,
    priceNote: "30-50개 묶음, 강도별 권장",
    aliases: ["빨래집게"],
    description: "핀치력 단계화에 필수. 약·중·강 강도별로 갖추면 이상적.",
  },
  {
    id: "kitchen-tongs",
    name: "요리 집게",
    category: "kitchen",
    type: "durable",
    priceMin: 3000,
    priceMax: 10000,
    aliases: ["요리 집게", "집게", "핀셋"],
    description: "콩·솜공 옮기기 등 정밀 도구 사용 task에 적합.",
  },
  {
    id: "scarf",
    name: "시폰 스카프",
    category: "craft",
    type: "durable",
    priceMin: 5000,
    priceMax: 15000,
    priceNote: "6-12장 색깔별",
    aliases: ["스카프", "시폰", "천"],
    description: "가볍고 부드러워 던지기·휘두르기 모두 안전.",
  },
  {
    id: "frying-pan-toy",
    name: "장난감 프라이팬",
    category: "kitchen",
    type: "durable",
    priceMin: 5000,
    priceMax: 15000,
    aliases: ["프라이팬", "팬"],
    description: "부침개 뒤집기 등 ADL 시뮬레이션에 필수. 가벼운 것만.",
  },
  {
    id: "spatula-toy",
    name: "뒤집개",
    category: "kitchen",
    type: "durable",
    priceMin: 2000,
    priceMax: 5000,
    aliases: ["뒤집개"],
    description: "실리콘 권장. 손목 회내·외 운동 task의 핵심.",
  },
  {
    id: "jenga",
    name: "젠가",
    category: "craft",
    type: "durable",
    priceMin: 10000,
    priceMax: 30000,
    aliases: ["젠가"],
    description: "양손 협응·집중력. 어르신 인기.",
  },
  {
    id: "yutnori",
    name: "윷놀이",
    category: "craft",
    type: "durable",
    priceMin: 5000,
    priceMax: 20000,
    aliases: ["윷", "윷놀이"],
    description: "전통 게임. 던지기 + 사회적 참여 + 회상 자극.",
  },
  {
    id: "mini-curling",
    name: "미니 컬링",
    category: "sport",
    type: "durable",
    priceMin: 20000,
    priceMax: 50000,
    aliases: ["미니컬링", "컬링"],
    description: "거리 조절·전략. 좌석에서도 가능.",
  },
  {
    id: "toy-gun",
    name: "장난감 총",
    category: "sport",
    type: "durable",
    priceMin: 5000,
    priceMax: 30000,
    aliases: ["장난감 총", "총"],
    description: "조준·인지·재미. 안전한 폼탄/물총 권장.",
  },
  {
    id: "gym-ball",
    name: "짐볼",
    category: "ball",
    type: "durable",
    priceMin: 15000,
    priceMax: 40000,
    priceNote: "직경 45-65cm",
    aliases: ["짐볼", "큰 공", "큰 부드러운 공"],
    description: "체간 안정·그룹 패스 게임. 가벼울수록 좋음.",
  },
  {
    id: "soft-ball",
    name: "소프트 볼",
    category: "ball",
    type: "durable",
    priceMin: 3000,
    priceMax: 10000,
    aliases: ["소프트볼", "부드러운 공", "축구공"],
    description: "안전한 던지기·차기. 어르신·아동 모두.",
  },
  {
    id: "bowling-pin",
    name: "볼링핀·PVC 막대",
    category: "sport",
    type: "durable",
    priceMin: 10000,
    priceMax: 25000,
    priceNote: "5-10개 세트",
    aliases: ["볼링핀", "막대", "핀", "PVC", "수영 누들", "노들"],
    description: "쓰러뜨리기·당구놀이·골 표시 등.",
  },
  {
    id: "picture-cards",
    name: "그림 카드",
    category: "card",
    type: "durable",
    priceMin: 3000,
    priceMax: 15000,
    priceNote: "16-30장 세트",
    aliases: ["그림 카드", "카드"],
    description: "기억력 짝짓기·인지 분류. 대비 강한 이미지 권장.",
  },
  {
    id: "golf-ball",
    name: "골프공·작은 공",
    category: "ball",
    type: "durable",
    priceMin: 5000,
    priceMax: 15000,
    aliases: ["골프공", "작은 공"],
    description: "손골프·정밀 굴리기. 부드러운 폼볼이 안전.",
  },
  {
    id: "color-chips",
    name: "색·숫자 칩",
    category: "craft",
    type: "consumable",
    priceMin: 5000,
    priceMax: 10000,
    priceNote: "30-50개 묶음",
    aliases: ["색깔 칩", "칩", "색·숫자"],
    description: "색 변별·인지 분류 task. 3cm 이상 크기 권장.",
  },
  {
    id: "beans-mixed",
    name: "잡곡·콩",
    category: "misc",
    type: "consumable",
    priceMin: 3000,
    priceMax: 8000,
    priceNote: "각 종류 200-300g",
    aliases: ["콩", "강낭콩", "검정콩", "렌즈콩", "완두콩"],
    description: "분류 task용. 알레르기·삼킴 주의.",
  },
  {
    id: "griptok",
    name: "그립톡·캐릭터 인형",
    category: "misc",
    type: "durable",
    priceMin: 5000,
    priceMax: 15000,
    aliases: ["그립톡", "캐릭터 인형", "인형"],
    description: "안구 추적 시각 자극용 손에 들기 좋은 작은 물체.",
  },
  {
    id: "mat",
    name: "안전 매트",
    category: "furniture",
    type: "durable",
    priceMin: 20000,
    priceMax: 100000,
    aliases: ["매트", "안전 매트"],
    description: "선 자세 게임 시 낙상 완충.",
  },
  {
    id: "table",
    name: "테이블",
    category: "furniture",
    type: "durable",
    priceMin: 0,
    priceMax: 0,
    priceNote: "치료실 기본 구비",
    aliases: ["테이블"],
    description: "팔꿈치 90°가 되는 높이가 이상적.",
  },
  {
    id: "chair",
    name: "의자·휠체어",
    category: "furniture",
    type: "durable",
    priceMin: 0,
    priceMax: 0,
    priceNote: "치료실 기본 구비",
    aliases: ["의자", "휠체어"],
    description: "좌석 안정성·브레이크 잠금 점검 필수.",
  },
  {
    id: "timer",
    name: "초시계·타이머",
    category: "misc",
    type: "durable",
    priceMin: 3000,
    priceMax: 15000,
    aliases: ["초시계", "타이머"],
    description: "스마트폰 타이머로 대체 가능.",
  },
  {
    id: "music-player",
    name: "음악 재생기",
    category: "misc",
    type: "durable",
    priceMin: 0,
    priceMax: 0,
    priceNote: "스마트폰 + 스피커로 충분",
    aliases: ["음악", "재생기", "배경 음악"],
    description: "리듬 게임·박자 동기화에 필요. 60-90 BPM 권장.",
  },
  {
    id: "tape-marker",
    name: "마스킹 테이프",
    category: "craft",
    type: "consumable",
    priceMin: 2000,
    priceMax: 5000,
    aliases: ["테이프", "출발선", "측정선", "마스킹"],
    description: "거리 표시·출발선 등에 다용도.",
  },
  {
    id: "vinyl-tunnel",
    name: "비닐 터널",
    category: "sport",
    type: "consumable",
    priceMin: 10000,
    priceMax: 30000,
    aliases: ["비닐터널", "터널"],
    description: "유아·소집단 운동에 인기. 사용 빈도에 따라 1-2년 교체.",
  },
  {
    id: "cotton-ball",
    name: "솜공·작은 물건",
    category: "misc",
    type: "consumable",
    priceMin: 3000,
    priceMax: 8000,
    aliases: ["솜공", "구슬", "작은 물건", "작은 블록"],
    description: "집게·핀셋 task에 옮길 대상. 색깔별 묶음.",
  },
  {
    id: "whiteboard",
    name: "점수판·화이트보드",
    category: "furniture",
    type: "durable",
    priceMin: 10000,
    priceMax: 50000,
    aliases: ["점수판", "화이트보드"],
    description: "팀 점수·라운드 기록. 종이로 대체 가능.",
  },
];

export function getToolById(id: string): ToolDef | undefined {
  return TOOLS_MASTER.find((t) => t.id === id);
}
